version: '3'

services:
  openvpn-client:
    build: ./build
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - /var/run/dbus/:/var/run/dbus/
    restart: unless-stopped
